"""
_draco_vendored.py — two small, self-contained functions copied from
cryoet-data-portal-neuroglancer (https://github.com/chanzuckerberg/cryoet-data-portal-neuroglancer),
so this project no longer needs that repo cloned as an external sibling directory.

Everything these two functions call (igneous.task_creation, taskqueue.LocalTaskQueue) is
a real, independently pip-installed package (igneous/zmesh/DracoPy) -- NOT part of the
cryoet-data-portal-neuroglancer repo itself. That repo's own code contribution here is
just the two functions below: a thin orchestration wrapper and a chunk-size calculation.
Everything else that file (cryoet_data_portal_neuroglancer/precompute/mesh.py) contains
(glb-mesh-specific helpers, segment-properties writing, etc.) is NOT copied here because
mesh_compression doesn't need it -- segment_properties is written by
mesh_compression.cleanup's own _write_segment_properties-equivalent caller instead.

------------------------------------------------------------------------------------
MIT License

Copyright (c) 2024-Present Chan Zuckerberg Initiative

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
------------------------------------------------------------------------------------
"""
from __future__ import annotations

import logging
from pathlib import Path

import igneous.task_creation as tc
import numpy as np
from taskqueue import LocalTaskQueue

LOGGER = logging.getLogger(__name__)


def determine_chunk_size_for_lod(
    mesh_shape: tuple[int, int, int] | np.ndarray,
    max_lod: int,
    min_chunk_dim: int = 16,
) -> tuple[tuple[tuple[int, int, int], tuple[int, int, int]], int]:
    """Determine the chunk size for a given mesh shape and LOD levels.

    The multi-resolution mesh is generated by decimating the mesh by a factor of 2 for
    each level of detail. The decimated meshes are placed into an octree structure to
    represent the LODs. This function determines the needed chunk size for the highest
    resolution mesh representation, which is the first LOD.
    """
    mesh_shape_arr: np.ndarray = np.array(mesh_shape)

    def _determine_chunk_shape_for_lod(shape, lod_level):
        return 2 ** np.floor(np.log2(shape / 2**lod_level))

    chunk_shape = _determine_chunk_shape_for_lod(mesh_shape_arr, max_lod)

    if np.any(chunk_shape < min_chunk_dim):
        max_lod = int(max(np.min(np.log2(mesh_shape_arr / min_chunk_dim)), 0))
        chunk_shape = _determine_chunk_shape_for_lod(mesh_shape_arr, max_lod)
    final_lod = int(max(np.min(np.log2(mesh_shape_arr / chunk_shape)), 0)) + 1
    LOGGER.info("Will produce %i LODs for this mesh at min size %s", final_lod, chunk_shape)
    x, y, z = chunk_shape.astype(int)

    acs_x, acs_y, acs_z = np.ceil(mesh_shape_arr / 2 ** (final_lod - 1))

    return (((int(acs_x), int(acs_y), int(acs_z)), (int(x), int(y), int(z))), final_lod)


def generate_multiresolution_mesh_from_segmentation(
    precomputed_segmentation_path: str | Path,
    mesh_directory: str,
    max_lod: int,
    mesh_shape: tuple[int, int, int] | np.ndarray,
    min_mesh_chunk_dim: int = 16,
    max_simplification_error: int = 10,
) -> None:
    """Generate a multi-resolution Draco mesh for a segmentation stored in precomputed
    format (zmesher meshing + Draco compression + multi-LOD sharding).

    max_simplification_error: geometric error tolerance passed to zmesher. Lower is
    gentler (less detail removed), higher is more aggressive. 0 disables simplification.
    """
    tq = LocalTaskQueue()
    path = f"precomputed://file://{precomputed_segmentation_path}"

    LOGGER.info("Generating mesh for %s", path)
    LOGGER.debug("Meshing with zmesher and %i max simplification error", max_simplification_error)
    simplification = max_simplification_error != 0
    tasks = tc.create_meshing_tasks(
        path,
        mip=0,
        shape=(256, 256, 256),
        mesh_dir=mesh_directory,
        sharded=True,
        fill_missing=False,
        max_simplification_error=max_simplification_error,
        simplification=simplification,
    )
    tq.insert(tasks)
    tq.execute()

    LOGGER.debug("Creating mesh manifest")
    tasks = tc.create_mesh_manifest_tasks(path, mesh_dir=mesh_directory, magnitude=3)
    tq.insert(tasks)
    tq.execute()

    LOGGER.debug("Creating multi-resolution mesh with max %i LOD", max_lod)
    (_, min_chunk_size), num_lods = determine_chunk_size_for_lod(mesh_shape, max_lod, min_mesh_chunk_dim)
    LOGGER.info("Generating %i LODs for the mesh", num_lods)
    tasks = tc.create_sharded_multires_mesh_tasks(
        path,
        mesh_dir=mesh_directory,
        num_lod=max_lod,
        min_chunk_size=min_chunk_size,
    )
    tq.insert(tasks)
    tq.execute()
