# Use Node.js base image
FROM node:16-bullseye-slim

# Set working directory
WORKDIR /app

# Copy package files
COPY applications/virtual-fly-brain/client/package.json ./
COPY applications/virtual-fly-brain/client/yarn.lock ./

# Install dependencies
RUN yarn install

# Copy frontend code
COPY applications/virtual-fly-brain/client/src ./src
COPY applications/virtual-fly-brain/client/public ./public
COPY applications/virtual-fly-brain/client/tsconfig.json ./
COPY applications/virtual-fly-brain/client/webpack.config.js ./
COPY applications/virtual-fly-brain/client/webpack.config.dev.js ./

# Build application
RUN yarn build

# Expose port
EXPOSE 3000

# Command to run the application
CMD ["yarn", "start"]
