harness:
  subdomain: virtual-fy-brain
  secured: false
  service:
    port: 8080
    auto: true
  deployment:
    auto: true
    port: 8080
    resources:
      requests:
        memory: 1512Mi
        cpu: 500m
      limits:
        memory: 3048Mi
        cpu: 1000m
  dependencies:
    build:
      - cloudharness-base-debian
      - cloudharness-flask
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
