harness:
  subdomain: virtual-fy-brain
  secured: false
  service:
    port: 8080
    auto: true

  deployment:
    auto: true
    port: 8080
  dependencies:
    build:
      - cloudharness-base-debian
      - cloudharness-flask
    soft:
    - argo