harness:
  subdomain: virtual-fy-brain
  secured: false
  service:
    port: 8080
    auto: true
  deployment:
    auto: true
    port: 8080
    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 1536Mi
        cpu: 750m
  dependencies:
    build:
      - cloudharness-base-debian
      - cloudharness-flask
    soft:
    - argo
