harness:
  subdomain: virtual-fy-brain
  secured: false
  service:
    port: 8080
    auto: true

  database:
    type: postgres
    auto: true
    name: virtual-fy-brain-db
    image_ref: virtual-fy-brain-postgres
    size: 240Gi
    resources:
      requests:
          memory: 2Gi
          cpu: 1
      limits:
        memory: 4Gi
        cpu: 2
    args: ["--vm", "1", "--vm-bytes", "8Gi", "--vm-hang", "1"]
  deployment:
    auto: true
    port: 8080
  dependencies:
    build:
      - cloudharness-base-debian
      - cloudharness-flask
      - virtual-fy-brain-postgres
    soft:
    - argo