harness:
  subdomain: virtual-fy-brain
  secured: false
  service:
    port: 8080
    auto: true
  deployment:
    auto: true
    port: 8080
    resources:
      requests:
        memory: 1512Mi
        cpu: 1000m
      limits:
        memory: 3048Mi
        cpu: 2000m
  dependencies:
    build:
      - cloudharness-base-debian
      - cloudharness-flask
