harness:
  subdomain: virtual-fy-brain
  secured: false
  service:
    port: 8080
    auto: true
  deployment:
    auto: true
    port: 8080
    resources:
      requests:
        memory: 512Mi
        cpu: 500m
      limits:
        memory: 1024Mi
        cpu: 1000m
  dependencies:
    build:
      - cloudharness-base-debian
      - cloudharness-flask
