export const getQueriesTypes = Object.freeze({
  GET_QUERIES_SUCCESS : 'GET_QUERIES_SUCCESS',
  DELETE_QUERY : 'DELETE_QUERY',
  GET_QUERIES_STARTED : 'GET_QUERIES_STARTED',
  GET_QUERIES_FAILURE : 'GET_QUERIES_FAILURE',
  UPDATE_QUERIES : 'UPDATE_QUERIES',
})
