openapi: 3.0.2
info:
  title: VirtualFlyBrainIndex
  version: 1.0.0
servers:
- url: /
tags:
- name: test
paths:
  /test:
    description: Test API.
    get:
      description: Test API.
      operationId: test_api
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: ok
      summary: Test API
      tags:
      - test
      x-openapi-router-controller: virtual_fly_brain.controllers.test_controller
    summary: Test API
  /data/{id}:
    description: Retrieve stack viewer images given an ID.
    get:
      description: Retrieve stack viewer images.
      operationId: get_term_info
      parameters:
      - description: VFB ID to search.
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: ok
      summary: Get stack viewer images for an ID
      tags:
      - Stack Viewer
      x-openapi-router-controller: virtual_fly_brain.controllers.default_controller
    summary: Stack viewer images API
components:
  schemas: {}
