openapi: 3.0.2
info:
  title: VirtualFlyBrainIndex
  version: 1.0.0
servers:
- url: /
tags:
- name: test
paths:
  /test:
    description: Test API.
    get:
      description: Test API.
      operationId: test_api
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: ok
      summary: Test API
      tags:
      - test
      x-openapi-router-controller: virtual_fly_brain.controllers.default_controller
    summary: Test API
