---
root: true
extends:
  - eslint:recommended
  - plugin:react/recommended
parser: "@babel/eslint-parser"
parserOptions:
  ecmaFeatures:
    jsx: true
plugins:
  - jest
  - react
  - react-hooks
settings:
  react:
    version: detect
env:
  jest/globals: true
  browser: true
  es6: true
rules:
  no-console: 0
  func-style: 0
  no-dupe-keys : 0
  global-require: 1
  no-unused-vars : 0
  consistent-return: 0
  prefer-arrow-callback:
    - 2
    - allowNamedFunctions: false
      allowUnboundThis: false
  jest/no-disabled-tests: 2
  jest/no-focused-tests: 2
  react/prop-types: 0
  react/forbid-prop-types: 0
  react/no-unused-prop-types: 0
  react-hooks/rules-of-hooks: 2
globals:
  __dirname: writable
  module: writable
