export const getInstancesTypes = Object.freeze({
  GET_INSTANCES_SUCCESS : 'GET_INSTANCES_SUCCESS',
  GET_INSTANCES_STARTED : 'GET_INSTANCES_STARTED',
  GET_INSTANCES_FAILURE : 'GET_INSTANCES_FAILURE',
  REMOVE_INSTANCES_SUCCESS : 'REMOVE_INSTANCES_SUCCESS',
  REMOVE_INSTANCES_FAILURE : 'REMOVE_INSTANCES_FAILURE'
})