export const getInstancesTypes = Object.freeze({
  GET_INSTANCES_SUCCESS : 'GET_INSTANCES_SUCCESS',
  GET_INSTANCES_STARTED : 'GET_INSTANCES_STARTED',
  GET_INSTANCES_FAILURE : 'GET_INSTANCES_FAILURE',
  REMOVE_INSTANCES_SUCCESS : 'REMOVE_INSTANCES_SUCCESS',
  REMOVE_INSTANCES_FAILURE : 'REMOVE_INSTANCES_FAILURE',
  SHOW_INSTANCE : 'SHOW_INSTANCE',
  HIDE_INSTANCE : 'HIDE_INSTANCE',
  CHANGE_COLOR : 'CHANGE_COLOR',
  FOCUS_INSTANCE : 'FOCUS_INSTANCE',
  FOCUSED_INSTANCE : 'FOCUSED_INSTANCE',
  SELECT_INSTANCE : 'SELECT_INSTANCE',
  SHOW_SKELETON : 'SHOW_SKELETON',
  HIDE_SKELETON : 'HIDE_SKELETON',
  SHOW_CYLINDERS : 'SHOW_CYLINDERS',
  HIDE_CYLINDERS : 'HYDE_CYLINDERS'
})