export const getLayoutTypes = Object.freeze({
  SHOW_WIDGET : 'SHOW_WIDGET',
  LOAD_CUSTOM_LAYOUT : 'LOAD_CUSTOM_LAYOUT',
  AUTOSAVE_LAYOUT : 'AUTOSAVE_LAYOUT',
  ACTIVATE_IMAGES : 'ACTIVATE_IMAGES',
  ACTIVATE_CIRCUITS : 'ACTIVATE_CIRCUITS',
})
