export const getOBJ3DTypes = Object.freeze({
  GET_3D_OBJ_TYPE_SUCCESS : 'GET_3D_OBJ_TYPE_SUCCESS',
  GET_3D_OBJ_TYPE_STARTED : 'GET_3D_OBJ_TYPE_STARTED',
  GET_3D_OBJ_TYPE_FAILURE : 'GET_3D_OBJ_TYPE_FAILURE'
})