export const getStackViewerTypes = Object.freeze({
  GET_TERM_INFO_SUCCESS : 'GET_TERM_INFO_SUCCESS',
  GET_TERM_INFO_STARTED : 'GET_TERM_INFO_STARTED',
  GET_TERM_INFO_FAILURE : 'GET_TERM_INFO_FAILURE'
})