export const getGlobalTypes = Object.freeze({
  GET_TEMPLATE_ID : 'GET_TEMPLATE_ID',
  SET_TEMPLATE_ID : 'SET_TEMPLATE_ID',
  ADD_RECENT_SEARCH : 'ADD_RECENT_SEARCH',
  REMOVE_RECENT_SEARCH : 'REMOVE_RECENT_SEARCH',
  REMOVE_ALL_RECENT_SEARCH : 'REMOVE_ALL_RECENT_SEARCH',
  OPEN_TERM_INFO : 'OPEN_TERM_INFO',
  OPEN_QUERY_COMPONENT : 'OPEN_QUERY_COMPONENT',
  FIRST_ID_LOADED : 'FIRST_ID_LOADED',
  ALIGN_TEMPLATES : 'ALIGN_TEMPLATES',
  RESET_ERRORS : 'RESET_ERRORS'
})
