version: '1.0'
stages:
- prepare
- build
- deploy
- publish
steps:
  prepare_deployment:
    title: Prepare helm chart
    image: python:3.9.10
    stage: prepare
    working_directory: .
    commands:
    - bash cloud-harness/install.sh
    - harness-deployment cloud-harness . -t ${{CF_BUILD_ID}} -d ${{DOMAIN}} -r ${{REGISTRY}} -i pub-chem-index
      -rs ${{REGISTRY_SECRET}} -e dev -n ${{NAMESPACE}}
